### ISSUE TITLE
Schedule WG Meetings!

### ISSUE THREAD

**Issue by dlorenc** [ossf/wg-developer-identity#11]
Now that we're public, we need to start scheduling our working group meetings. Let's plan on sending out a doodle poll next week to give people time to find this repo and get on the discussion list.

If you're interested in participating, please join the group here: https://groups.google.com/forum/#!forum/ossf-wg-developer-identity

**Comment by dlorenc** [comment]
Doodle poll here: https://doodle.com/poll/cqdmkrdems8uqe6x

**Comment by dlorenc** [comment]
The first meeting has been scheduled! Here is the calendar invite: https://calendar.google.com/event?action=TEMPLATE&tmeid=MG12bWhyNzYyYmU1N3M2bHFqZmdibXY3NnIgZGxvcmVuY0Bnb29nbGUuY29t&tmsrc=dlorenc%40google.com

It is Wednesday, August 19th at 9AM Pacific time.

**Comment by dlorenc** [comment]
The first meeting has been scheduled! We need to create a public calendar to make it easy to add, but for now please join the Google group listed above.

The meeting is Wednesday, August 19th at 9AM Pacific.

**Comment by lukehinds** [comment]
Do we have a zoom room we should join (it might be in the google calender, but that's not opening for me).

**Comment by dlorenc** [comment]
I don't know if we have a zoom setup yet. Does Google Hangouts work? Here's the link: meet.google.com/nmy-thie-pqd

**Comment by axelsimon** [comment]
Google Meet (formerly Hangouts or Hangouts Meet, or some other confusing thing) allows for non-Google users to attend too.

Another option is [Jitsi Meet](meet.jit.si) which i have had good experience with (and others have told me they haven't so much).
