### ISSUE TITLE
Scope: extend to supply chain identities more broadly?

### ISSUE THREAD

**Issue by kaywilliams** [ossf/wg-developer-identity#9]
In a supply chain there are many identities related to software, hardware, machines, service, people. Let's think about how to validate identities more broadly?

**Comment by dlorenc** [comment]
Are you referring to the identity of a machine or service? Or just saying we want to trace identities across these boundaries?

**Comment by mayakacz** [comment]
> In a supply chain there are many identities related to software, hardware, machines, service, people. Let's think about how to validate identities more broadly?

Can you clarify?

I'd be much more interested in focusing on the *validity* of a *commit* or *contribution* than on the *identity* of a *developer*. For example, a developer's commits may be valid prior to an account compromise, but invalid after an account compromise. The developer's identity does not help detect or validate this.

**Comment by mpeters** [comment]
>  The developer's identity does not help detect or validate this.

It's not sufficient, but it does help. There is of course a temporal component to validity and identity. A compromise is an event that terminate an identity being valid, but so can quitting or being fired or removed from a community. I think validity definitely depends on identity even if it needs more.

**Comment by kaywilliams** [comment]
Let's close this issue as it is being discussed in other places:

https://github.com/ossf/wg-developer-identity/issues/19
https://github.com/ossf/wg-developer-identity/pull/15
